### ISSUE TITLE
Not compatible with flake8 v5 or v6

### ISSUE THREAD

**Issue by wwuck** [decorator-factory/flake8-useless-assert#3]
Can we bump up or remove the restriction on flake8 upper bound version?

https://iscinumpy.dev/post/bound-version-constraints/

**Comment by decorator-factory** [comment]
It's fixed in 0.4.4!

(sorry for the enormous delay, I didn't realize someone was actually using this)

**Comment by decorator-factory** [comment]
I suppose I got carried away with my experience with depending on `package-a>=1.2.3` (which depends on `package-a>=2.0.0`) in applications without pinning transitive dependencies, and when `package-b==3.0.0` comes out with an entirely new API, we're no longer building
